---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  type: NodePort
  ports:
  - name: game
    port: 25565
    targetPort: 25565
    nodePort: 30000
    protocol: TCP
  selector:
    app: game
    game: minecraft
    modpack: vanilla
