---
apiVersion: v1
kind: Secret
metadata:
  name: tls-pages
  namespace: gitlab-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
