---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
      version: v1
  template:
    metadata:
      labels:
        app: jellyfin
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
        maistra.io/expose-route: 'true'
    spec:
      serviceAccountName: default
      containers:
      - name: media-server
        image: docker.io/jellyfin/jellyfin:latest
        command:
        - /jellyfin/jellyfin
        envFrom:
        - configMapRef:
            name: jellyfin
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 1000m
            memory: 4Gi
        ports:
        - name: http
          containerPort: 8096
        - name: https
          containerPort: 8920
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: jellyfin-media-pvc
          mountPath: /media
        - name: jellyfin-config-pvc
          mountPath: /config
        - name: jellyfin-cache-pvc
          mountPath: /cache
      volumes:
      - name: jellyfin-media-pvc
        persistentVolumeClaim:
          claimName: jellyfin-media
      - name: jellyfin-config-pvc
        persistentVolumeClaim:
          claimName: jellyfin-config
      - name: jellyfin-cache-pvc
        persistentVolumeClaim:
          claimName: jellyfin-cache
