---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
    service: server
spec:
  type: ClusterIP
  selector:
    app: jellyfin
  ports:
  - name: http
    protocol: TCP
    port: 8096
    targetPort: 8096
  - name: https
    protocol: TCP
    port: 8920
    targetPort: 8920
