---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft-direwolf20-v118

commonLabels:
  app: game
  game: minecraft
  modpack: direwolf20-v1.18
  modpack-id: "95"
  modpack-type: forge
  modpack-source: Feed-The-Beast
  modpack-version: v1.9.1
  modpack-version-id: "2239"

bases:
- ../../base

# resources:
# - namespace.yaml
# - data.yaml

configMapGenerator:
- name: minecraft-env
  envs: 
  - config/environment.txt
- name: minecraft-server-files
  files:
  - ops.json=config/ops.json
  - whitelist.json=config/whitelist.json
  # - vt-datapacks.json=config/vt-datapacks.json
  # - vt-craftingtweaks.json=config/vt-craftingtweaks.json
  # - vt-resourcepacks.json=config/vt-resourcepacks.json

patches:
# patchesJson6902:
- target:
    version: v1
    kind: Service
    name: minecraft-server
  path: patches/service.yaml
- target:
    version: v1
    kind: Deployment
    name: minecraft-server
  path: patches/deployment.yaml
- target:
    version: v1
    kind: Namespace
    name: minecraft
  patch: |-
    - op: replace
      path: /metadata/name
      value: minecraft-direwolf20-v118
