apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secrets/tls/gitlab.yaml
- secrets/tls/kas.yaml
- secrets/tls/minio.yaml
- secrets/tls/pages.yaml
- secrets/tls/registry.yaml
- gitlab.yaml
