---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-home-assistant-config
  labels:
    fstype: nfs
    app: home-assistant
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /volume1/docker/home-assistant
    server: synology
  persistentVolumeReclaimPolicy: Retain
