---
apiVersion: v1
kind: Secret
metadata:
  name: github-cluster-hub
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/hyperkineticnerd/gitops.git

