apiVersion: v1
kind: Secret
metadata:
  name: gitlab-private-repo-creds
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  type: git
  url: https://MyGitServer/MyNamespace/MyGitRepo.git
  username: MyUserName
  password: MySuperSecretPassword
  sshPrivateKey: ** Private SSH Key **
