kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  to:
    kind: Service
    name: server
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
