apiVersion: v1
kind: Service
metadata:
  name: rrdcached
  namespace: librenms
spec:
  type: ClusterIP
  selector:
    app: librenms
    component: rrdcached
  ports:
    - name: rrdcached
      port: 42217
      targetPort: 42217
      protocol: TCP
