{{ if not (empty .Values.securityContext) }}
{{ if not .Values.securityContext.runAsNonRoot }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-scc-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: librenms
    namespace: {{ .Release.Namespace }}
  {{- if .Values.mysql.enabled }}
  - kind: ServiceAccount
    name: librenms-mysql
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  - kind: ServiceAccount
    name: librenms-redis
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{ end }}
{{ end }}
