apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/odf-lvm-operator.openshift-storage: ""
  name: odf-lvm-operator
  namespace: openshift-storage
spec:
  channel: stable-4.11
  installPlanApproval: Automatic
  name: odf-lvm-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-lvm-operator.v4.11.2
