apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
  namespace: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
      version: v1
  template:
    metadata:
      labels:
        app: homebridge
        version: v1
    spec:
      serviceAccountName: default
      containers:
      - name: homebridge
        image: docker.io/oznu/homebridge:latest
        envFrom:
        - configMapRef:
            name: homebridge
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
        ports:
        - name: http
          containerPort: 8581
        securityContext:
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: config
          mountPath: /homebridge
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homebridge-config
