---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-homebridge-config
  labels:
    fstype: nfs
    app: homebridge
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /volume1/docker/homebridge
    server: synology
  persistentVolumeReclaimPolicy: Retain
