---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-config
  namespace: homebridge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-homebridge-config
  storageClassName: ""
