---
apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
  labels:
    app: homebridge
    service: server
spec:
  type: ClusterIP
  selector:
    app: homebridge
  ports:
  - name: http
    protocol: TCP
    port: 8581
    targetPort: 8581
