kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: homebridge
  namespace: homebridge
spec:
  to:
    kind: Service
    name: homebridge
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
