kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  to:
    name: home-assistant
    kind: Service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
